# -*- coding: utf-8 -*-
"""BIS LAB 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EWuRVqS1DHm4Y8EozDpCdm4n_x7NJtdu
"""

import random
import copy
import pandas as pd

# Define configuration and constraints
COURSES = ["Math 101", "Math 201", "Physics 101","Physics 201", "Chemistry 101", "Biology 101", "History 101", "English 101"]
PROFESSORS = ["Dr. Smith", "Dr. Jackson","Dr. Jones", "Dr. Taylor","Dr. Maya", "Dr. Davis", "Dr. Miller", "Dr. Wilson"]
COURSE_PROF = {COURSES[i]: PROFESSORS[i] for i in range(len(COURSES))}

TIMESLOTS = ["9:00", "10:00", "11:00", "10:00","9:00", "11:00", "9:00", "11:00"]
ROOMS = ["Room A", "Room B", "Room C"]

class Timetable:
    def __init__(self):
        self.assignments = {}
        for course in COURSES:
            self.assignments[course] = {
                'prof': COURSE_PROF[course],
                'slot': random.choice(TIMESLOTS),
                'room': random.choice(ROOMS)
            }

    def clone(self):
        cloned = Timetable()
        cloned.assignments = copy.deepcopy(self.assignments)
        return cloned

def evaluate_fitness(timetable):
    """
    Evaluates fitness based on conflicts.
    Hard constraints:
    - A professor cannot teach two classes at the same slot.
    - A room cannot host two classes at the same slot.
    """
    conflicts = 0
    items = list(timetable.assignments.items())
    for i in range(len(items)):
        c1, data1 = items[i]
        for j in range(i + 1, len(items)):
            c2, data2 = items[j]
            if data1['slot'] == data2['slot']:
                if data1['prof'] == data2['prof']:
                    conflicts += 1
                if data1['room'] == data2['room']:
                    conflicts += 1
    return 1.0 / (1.0 + conflicts)

class Particle:
    def __init__(self):
        self.position = Timetable()
        self.velocity = {course: {'slot': 0.1, 'room': 0.1} for course in COURSES}
        self.pbest = self.position.clone()
        self.pbest_fitness = evaluate_fitness(self.pbest)

def solve_timetable_pso(num_particles=40, max_iterations=100, w=0.5, c1=1.5, c2=1.5):
    # Initialize swarm
    swarm = [Particle() for _ in range(num_particles)]

    # Find gbest
    gbest_particle = max(swarm, key=lambda p: p.pbest_fitness)
    gbest = gbest_particle.pbest.clone()
    gbest_fitness = gbest_particle.pbest_fitness

    for iteration in range(max_iterations):
        for p in swarm:
            fitness = evaluate_fitness(p.position)

            if fitness > p.pbest_fitness:
                p.pbest = p.position.clone()
                p.pbest_fitness = fitness

            if fitness > gbest_fitness:
                gbest = p.position.clone()
                gbest_fitness = fitness

        if gbest_fitness == 1.0:
            break  # Conflict-free schedule found

        # Update velocities and positions
        for p in swarm:
            for course in COURSES:
                # Calculate updates for slots and rooms independently
                for attribute in ['slot', 'room']:
                    choices = TIMESLOTS if attribute == 'slot' else ROOMS

                    # Attraction components
                    cognitive = c1 * random.random() * (1.0 if p.pbest.assignments[course][attribute] == p.position.assignments[course][attribute] else -1.0)
                    social = c2 * random.random() * (1.0 if gbest.assignments[course][attribute] == p.position.assignments[course][attribute] else -1.0)

                    # New velocity
                    p.velocity[course][attribute] = w * p.velocity[course][attribute] + cognitive + social

                    # Position update logic based on velocity sign
                    if p.velocity[course][attribute] < -0.5:
                        # Move towards global best
                        p.position.assignments[course][attribute] = gbest.assignments[course][attribute]
                    elif p.velocity[course][attribute] > 0.5:
                        # Move towards personal best
                        p.position.assignments[course][attribute] = p.pbest.assignments[course][attribute]
                    else:
                        # Mutate/Randomize choice for exploration
                        if random.random() < 0.15:
                            p.position.assignments[course][attribute] = random.choice(choices)

    return gbest, gbest_fitness

best_schedule, fitness = solve_timetable_pso(num_particles=50, max_iterations=150)
print(f"Final Best Schedule Fitness: {fitness:.4f} (1.0 is Perfect/Conflict-free)")

# Represent best schedule in a DataFrame
results = []
for course, details in best_schedule.assignments.items():
    results.append({
        "Course": course,
        "Professor": details["prof"],
        "Timeslot": details["slot"],
        "Room": details["room"]
    })

df_result = pd.DataFrame(results).sort_values(by=["Timeslot", "Room"])
display(df_result)

"""Imagine you are trying to arrange a school timetable so that no two teachers are in the same room at the same time, and no teacher is booked to teach two classes at once.

Here is how this algorithm works, in simple terms:

The Swarm (Our Team of Planners):

We create a team of 40 "planners" (the particles).
Each planner starts by creating a completely random timetable (this is their "position").
The Scorecard (Fitness):

We grade each timetable. A perfect timetable with zero double-bookings gets a score of 1.0.
Every time there is a clash (like Dr. Smith assigned to teach two classes at Mon 9:00), the score goes down.
Learning and Improving (The Optimization):

We keep track of the overall best schedule found by anyone in the group so far (global best).
Each planner also remembers the best schedule they personally created so far (personal best).
On every turn, each planner modifies their timetable by looking at those two success stories:
They have a tendency to copy the assignments from the global best timetable.
They also have a tendency to copy assignments from their own personal best timetable.
Sometimes, they make a completely random change (mutation) to see if they get lucky with a new idea.
The Goal:

This cycle repeats up to 150 times.
The planners keep sharing tips and adjusting their schedules until they successfully build a perfect, clash-free timetable (fitness = 1.0).

Here is how the timetable generation is mapped directly to standard Particle Swarm Optimization (PSO) terminology:

1. The Search Space
The search space represents all possible combinations of assignments. With 8 courses, 8 timeslots, and 3 rooms, there are $24^8$$24^8$ (over 110 billion) possible ways to build a schedule. The algorithm searches this discrete multi-dimensional space for a coordinate that resolves all conflicts.

2. Position ($X_i$$X_i$)
Each Particle in the swarm has a Position, which represents a candidate solution in the search space.

In this program, a particle's position is a complete Timetable object.
This position is a vector of coordinates representing the assigned Timeslot and Room for every course.
3. Fitness / Objective Function ($f(X)$$f(X)$)
In PSO, the objective function measures how close a particle's position is to the optimal solution.

Our fitness function evaluates the position by counting overlapping assignments (conflicts).
The objective is to maximize the fitness $f(X) = \frac{1}{1 + \text{conflicts}}$$f(X) = \frac{1}{1 + \text{conflicts}}$, searching for the target global maximum of $1.0$$1.0$ (0 conflicts).
4. Personal Best ($pbest_i$$pbest_i$)
Each particle remembers the coordinate of the best solution it has personally encountered during its path through the search space.

If a particle moves to a new position that results in fewer scheduling conflicts than its previous record, it updates its $pbest_i$$pbest_i$ to this new position.
5. Global Best ($gbest$$gbest$)
This is the single best coordinate discovered by any particle in the entire swarm throughout the history of the run.

The swarm constantly tracks this $gbest$$gbest$ position, which serves as a beacon pulling other particles toward the most promising area of the scheduling search space.
6. Velocity ($V_i$$V_i$) & Velocity Update
In traditional PSO, Velocity represents a step size and direction vector. In this discrete adaptation:

Velocity is a dictionary of real values mapping the propensity/tendency to change a specific course's timeslot or room.
On each step, the velocity is updated using the classic formula: $$V_{i} \leftarrow w \cdot V_{i} + c_1 \cdot r_1 \cdot (pbest_i - X_i) + c_2 \cdot r_2 \cdot (gbest - X_i)$$$$V_{i} \leftarrow w \cdot V_{i} + c_1 \cdot r_1 \cdot (pbest_i - X_i) + c_2 \cdot r_2 \cdot (gbest - X_i)$$
Inertia ($w$$w$): Keeps some momentum from its previous change direction.
Cognitive Component ($c_1 \cdot r_1$$c_1 \cdot r_1$): Attracts the particle back to its personal best setup.
Social Component ($c_2 \cdot r_2$$c_2 \cdot r_2$): Attracts the particle toward the global swarm leader ($gbest$$gbest$).
7. Position Update
The particle uses its newly calculated velocity to make its move. High velocity values trigger deterministic changes (copying values from $pbest$$pbest$ or $gbest$$gbest$), while low velocities introduce a stochastic (random) search element to escape local optima.
"""